name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 在编译前自动处理签名配置，无需手动改动源码仓库
      - name: Bypass custom signing config
        run: |
          sed -i 's/"universal"/"debug"/g' app/build.gradle.kts
          sed -i -E 's/(create|register)\s*\("debug"\)/\1("unused")/g' app/build.gradle.kts

      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DoNotTryAccessibility-Fixed
          path: app/build/outputs/apk/debug/*.apk
